AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Parameters:
  EnvType: 
    Description: Env in which u want to create
    Type: String
    AllowedValues: 
      - nprd
      - prd
Resources:

  ManagedPrefixList:
    Type: AWS::EC2::PrefixList
    Properties:
      PrefixListName: !Sub 'ManagedPrefixList-${EnvType}'
      AddressFamily: "IPv4"
      MaxEntries: 10
      Entries: 
        - Cidr: '10.10.0.0/24'  
        


Outputs:
  LogicalID:
    Description: Information about the value
    Value: !Ref ManagedPrefixList
    Export:
      Name: !Sub 'ManagedPrefixList-${EnvType}'

 